# -*- coding: utf-8 -*-
"""Comment_Toxicity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OTzysPRkJ_xHyanDKTUGKF_n4zEJYVpZ

Step 1: Load Dataset
"""

import pandas as pd

df_train = pd.read_csv('/content/train.csv')

print(df_train.shape)
print(df_train.info())
print(df_train.isnull().sum())
print(df_train.duplicated().sum())

print(df_train.head())

df_test = pd.read_csv('/content/test.csv')

print(df_test.shape)
print(df_test.info())
print(df_test.isnull().sum())
print(df_test.duplicated().sum())

print(df_test.head())

import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.feature_extraction.text import TfidfVectorizer

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

"""Test Processing"""

import pandas as pd
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Download NLTK resources
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt_tab') # Keep if specifically needed, but often 'punkt' is sufficient for tokenization

# Reload df to ensure 'comment_text' is string data
df = pd.read_csv('/content/train.csv')

# Initialize Objects
stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

# text cleaning

def clean_text(text):
  text = str(text).lower()
  # Replace newlines with space
  text = re.sub(r'\n', ' ', text)
  text = re.sub(r"http\S+|www\S+|https\S+","",text,flags = re.MULTILINE)
  text = re.sub(r"\@\w+|\#","",text)
  text = re.sub(r"[^a-zA-Z0-9]"," ",text)
  # Normalize whitespace: replace multiple spaces with a single space and strip leading/trailing spaces
  text = re.sub(r'\s+', ' ', text).strip()

  # tokenization
  words = word_tokenize(text)

  # stopword removal + lemmatization
  words = [
      lemmatizer.lemmatize(word)
      for word in words
      if word not in stop_words
  ]

  return " ".join(words)

df["comment_text"] = df["comment_text"].apply(clean_text)

df.head()

# TF-IDF Vectorization

tfidf = TfidfVectorizer(
    max_features=5000
)

X_tfidf = tfidf.fit_transform(
    df['comment_text']
)

print(
"TFIDF Shape:",
X_tfidf.shape
)

# Deep Learning Tokenizer

max_words = 10000
max_len = 100

tokenizer = Tokenizer(
    num_words=max_words
)

tokenizer.fit_on_texts(
    df['comment_text']
)

sequences = tokenizer.texts_to_sequences(
    df['comment_text']
)

X_pad = pad_sequences(
    sequences,
    maxlen=max_len
)

print(
"Padded Shape:",
X_pad.shape
)

df.to_csv("Train_processed_text.csv", index=False)
print("File is downloaded with all columns.")

import pandas as pd
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Download NLTK resources
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt_tab') # Keep if specifically needed, but often 'punkt' is sufficient for tokenization

# Reload df to ensure 'comment_text' is string data
df = pd.read_csv('/content/test.csv')

# Initialize Objects
stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

# text cleaning

def clean_text(text):
  text = str(text).lower()
  # Replace newlines with space
  text = re.sub(r'\n', ' ', text)
  text = re.sub(r"http\S+|www\S+|https\S+","",text,flags = re.MULTILINE)
  text = re.sub(r"\@\w+|\#","",text)
  text = re.sub(r"[^a-zA-Z0-9]"," ",text)
  # Normalize whitespace: replace multiple spaces with a single space and strip leading/trailing spaces
  text = re.sub(r'\s+', ' ', text).strip()

  # tokenization
  words = word_tokenize(text)

  # stopword removal + lemmatization
  words = [
      lemmatizer.lemmatize(word)
      for word in words
      if word not in stop_words
  ]

  return " ".join(words)

df["comment_text"] = df["comment_text"].apply(clean_text)

df.head()

# TF-IDF Vectorization

tfidf = TfidfVectorizer(
    max_features=5000
)

X_tfidf = tfidf.fit_transform(
    df['comment_text']
)

print(
"TFIDF Shape:",
X_tfidf.shape
)

# Deep Learning Tokenizer

max_words = 10000
max_len = 100

tokenizer = Tokenizer(
    num_words=max_words
)

tokenizer.fit_on_texts(
    df['comment_text']
)

sequences = tokenizer.texts_to_sequences(
    df['comment_text']
)

X_pad = pad_sequences(
    sequences,
    maxlen=max_len
)

print(
"Padded Shape:",
X_pad.shape
)

df.to_csv("Test_processed_text.csv", index=False)
print("File is downloaded with all columns.")

"""Label Creation"""

toxicity_columns = [
    'toxic',
    'severe_toxic',
    'obscene',
    'threat',
    'insult',
    'identity_hate'
]

y = df[toxicity_columns]

print(y.shape)
print(y.head())

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device}")

"""Train/Test"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_pad,
    y,
    test_size=0.2,
    random_state=42
)

"""RNN Model"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import SimpleRNN
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout
from tensorflow.keras.callbacks import (
    EarlyStopping,
    ReduceLROnPlateau
)

rnn_model = Sequential()

rnn_model.add(
    Embedding(
        input_dim=10000,
        output_dim=128
        # input_length=100  # Deprecated and removed
    )
)

rnn_model.add(
    SimpleRNN(
        64
    )
)

rnn_model.add(
    Dropout(.5)
)

rnn_model.add(
    Dense(
        6, # Changed from 1 to 6 to match the 6 toxicity labels
        activation='sigmoid'
    )
)

# Stop if validation loss stops improving
early_stop = EarlyStopping(
    monitor='val_loss',
    patience=2,
    restore_best_weights=True
)

# Reduce learning rate automatically
reduce_lr = ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.5,
    patience=1,
    verbose=1
)

rnn_model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

history = rnn_model.fit(
    X_train,
    y_train,
    epochs=15,
    batch_size=32,
    validation_split=0.2,
    callbacks=[
        early_stop,
        reduce_lr
    ]
)

loss, acc = rnn_model.evaluate(
    X_test,
    y_test
)

print("Test Accuracy:", acc)
print("Test Loss:", loss)

rnn_model.save(
    "rnn_model.h5"
)

# Save tokenizer

import pickle
import os

# Create the directory if it doesn't exist
os.makedirs('models_rnn', exist_ok=True)

pickle.dump(
    tokenizer,
    open(
        'models_rnn/tokenizer.pkl',
        'wb'
    )
)

print("Model and tokenizer saved")

"""LSTM Model"""

from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout
from tensorflow.keras.callbacks import EarlyStopping

lstm_model=Sequential()

lstm_model.add(
Embedding(
input_dim=10000,
output_dim=128
# input_length=100 # Deprecated and removed
)
)

lstm_model.add(
Bidirectional(
LSTM(
64
)
)
)

lstm_model.add(
Dropout(.3)
)

lstm_model.add(
Dense(
64,
activation='relu'
)
)

lstm_model.add(
Dense(
6, # Changed from 1 to 6 to match the 6 toxicity labels
activation='sigmoid'
)
)

lstm_model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=2,
    restore_best_weights=True
)

history = lstm_model.fit(
    X_train,
    y_train,
    epochs=15,
    batch_size=32,
    validation_split=0.2,
    callbacks=[early_stop]
)

loss, acc = lstm_model.evaluate(
    X_test,
    y_test
)

print("Test Accuracy:", acc)
print("Test Loss:", loss)

lstm_model.save(
    "lstm_model.h5"
)

# Save tokenizer

import pickle
import os

# Create the directory if it doesn't exist
os.makedirs('models_Lstm', exist_ok=True)

pickle.dump(
    tokenizer,
    open(
        'models_Lstm/tokenizer.pkl',
        'wb'
    )
)

print("Model and tokenizer saved")

"""Metrics"""

from sklearn.metrics import (
    f1_score,
    precision_score,
    recall_score
)

pred = lstm_model.predict(X_test)

pred = (pred > 0.5).astype(int)

print(
    "F1:",
    f1_score(
        y_test,
        pred,
        average='micro'
    )
)

print(
    "Precision:",
    precision_score(
        y_test,
        pred,
        average='micro'
    )
)

print(
    "Recall:",
    recall_score(
        y_test,
        pred,
        average='micro'
    )
)